apiVersion: gitkube.sh/v1alpha1
kind: Remote
metadata:
  name: sampleremote
  namespace: default
spec:
  ## uncomment to add a registry
  # registry:
  #   url: "registry.io/user"
  #   credentials:
  #     secretKeyRef:
  #       name: regsecret
  #       key: .dockercfg
  deployments:
  - name: www
    containers: 
    - name: www
      path: example/www
      dockerfile: example/www/Dockerfile
  authorizedKeys:
  - "ssh-rsa <key>"
