apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: www
    name: www
    namespace: default
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: www
      spec:
        containers:
        - image: hasura/hello-world:latest
          imagePullPolicy: IfNotPresent
          name: www
          ports:
          - containerPort: 8080
            protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: www
    name: www
    namespace: default
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: www
    type: ClusterIP
kind: List
metadata: {}
