apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: remotes.gitkube.sh
spec:
  group: gitkube.sh
  version: v1alpha1
  scope: Namespaced
  names:
    plural: remotes
    singular: remote
    kind: Remote
    shortNames:
    - rem
